### ISSUE TITLE
Question 3

### ISSUE THREAD

**Issue by samtay-dev** [Fakhruddin081/Task-#3]
Can you tell me what DHCP is? 

What is the difference between Static Ip vs Dynamic Ip?

**Comment by Fakhruddin081** [comment]
DHCP = dynamic Host Configuration Protoclol is a particular protocol which is used to assign a unique  IP addresses to any network device 
The  4  steps taken by the devices to obtain an address using DHCP. 
DHCPDiscover - Looks for a DHCP server
DHCPOffer - The DHCP server offers an address  
DHCPRequest - The host requests to lease the address 
DHCPACK - DHCP server sends the IP addresses to the host  



static vs dynamic ip

The static IP is provided byInternet sevice provider
whereas the Dynamcic IP address is provided by DHCP
static ip address does not change any time, it means if a static ip address is provided then it can’t be changed or modified.
but Dynamic address can be changed any time
static ip address is less secure comapred to dynamic ip address
The device designed by static ip address can be trace. but the designed Dynamic ip address cannot be traced
