### ISSUE TITLE
Question4

### ISSUE THREAD

**Issue by samtay-dev** [Fakhruddin081/Task-#4]
How does a web certificate work? (Website admin uploads a certificate with a public key and its corresponding private key. HTTPS communication is encrypted with this key pair. If the certificate is not recognized by a known CA, a web browser shows a warning)

**Comment by Fakhruddin081** [comment]
If an organization wants to have a secure website that uses encryption, 
it needs to obtain a site, or host, certificate
By making sure a website encrypts your information and has a valid certificate, 
you can help protect yourself against attackers who create malicious sites to gather your information
A message encrypted with a public key is used for secrecy
  -  The message can only be decrypted with the corresponding private key, 
but you cannot verify who the owner is.
 A message encrypted with a private key is used for authentication
  -  The message owner can be verified if you know the corresponding public key,
 but is not secret. 
  -  This is why a web browsers have a record of public keys for CA Authorities - 
so they can verify that a "public key certificate" is signed by the a real CA Authority
